'use strict';

module.exports = {
  "M":       "send",
  "I":       "int",
  "A":       "array",
  "B":       "begin",
  "F":       "if",
  "L":       "lvar",
  "Shift-L": "lvasgn",
  "Shift-O": "op_asgn",
  "S":       "str",
  "W":       "while",
  "G":       "arg",
  "Shift-G": "args",
  "Shift-B": "block",
  "C":       "class",
  "Shift-C": "const",
  "Shift-F": "false",
  "V":       "gvar",
  "H":       "hash",
  "P":       "pair",
  "Shift-S": "self",
  "Y":       "sym",
}
